Dev
anyatamax/Python_Clicker pull request #1
Opened 2021-04-04 14:13 UTC by anyatamax

2021-04-10 21:26 UTC, pkositsyn requested changes

2021-04-10 21:26 UTC, pkositsyn commented on Clicker/main.py
> +    global click_cost
Ай, ой, больно смотреть. Давай класс сделаем и туда положим

2021-04-10 21:26 UTC, pkositsyn commented on Clicker/main.py
> +from tkinter import *
Давай без звездочки. Либо from ... import ... as ..., либо import tkinter as tk и дальше уже через название модуля обращаемся

2021-04-10 21:26 UTC, pkositsyn commented on Clicker/main.py
> +mainloop()
Как минимум нужно унести под
```
if __name__ == "__main__":
    main()
```
А еще лучше сделать класс кликера, который будет взаимодействовать (инициализировать) с окошками

2021-04-15 19:15 UTC, anyatamax commented on Clicker/main.py
> +mainloop()
Я если что пофиксила, то что нужно было)

2021-04-20 15:38 UTC, pkositsyn approved these changes
Есть только довольно базовая функциональность, готов поставить +0.2 за UI

2021-04-20 15:38 UTC, pkositsyn commented on Clicker/ClickerClass.py
> +class CountClick:
Давай сделаем Enum

2021-11-23 20:15 UTC, merged